### PR TITLE
feat: add --file option

### LINKED ISSUE #222: Support for --file option
Is it possible to add support for the mocha '--file' option that would help in executing root level hooks?

### PR DESCRIPTION
**Pull request by Favna**
This will resolve #222 

Merging this PR adds the Mocha option for `--file` to have a single global setup file - with the caveats that @1999 shared in the issue discussion.

### CODE REVIEW

**Comment by 1999** [comment]
Looks like the test fails in mocha@6

**Comment by Favna** [comment]
@1999 I completely forgot about this pr in between all the other things. I just tried running the mocha 6 based tests locally and they seem to run just fine (log here: https://hasteb.in/urumavot.yaml). Can you give Travis a retry and confirm it wasn't just some weird flakyness?

**Comment by Favna** [comment]
There is indeed some kind of flakyness. Now it broke on Mocha v4.

**Comment by FlyingPumba** [comment]
@1999 @Favna I could use this feature as well to execute root level hooks for each test case (i.e., defining beforeEach and afterEach at the root level). Is there any workaround available in the meantime?

BTW, I tried downloading the fork as a github dependency on my project (using `npm install --save-dev Favna/mocha-parallel-tests#feat/file_option`) but it fails to build with errors:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/src/my_project/node_modules/mocha-parallel-tests/dist/bin/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/src/my_project/node_modules/mocha-parallel-tests/dist/bin/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Am I doing something wrong? The same happens if I try to run: `npm install --save-dev mocha-parallel/mocha-parallel-tests`

**Comment by Favna** [comment]
@FlyingPumba TypeScript written packages cannot *really* be installed from GitHub unless you manually go into `node_modules/mocha-parallel-test` and run `npm run build`. Since the main field in package.json will reference the compiled JS, but the source code (from GitHub) only has the source TypeScript files.

**Comment by FlyingPumba** [comment]
@Favna That makes sense, thanks. I will try to set it up locally.

**Comment by 1999** [comment]
@Favna I wouldn't say it's flaky - the tests always fail on the newly added "file" test case. Sorry, I don't have enough time to look into this project now.

**Comment by 1999** [comment]
I will fix it on my own.

**Comment by Favna** [comment]
@1999 tyvm

**Comment by 1999** [comment]
https://github.com/mocha-parallel/mocha-parallel-tests/pull/277

**Pull request closed without merging**
