### PR TITLE
fix: circular json stringify

### PR DESCRIPTION
**Pull request by Stngle**
image

when i use the npm package `circular-json`, it throws an error `RangeError: Maximum call stack size exceeded`. 

when i use the npm package `safe-json-stringify`, the problem fixed.

### CODE REVIEW

**Comment by Stngle** [comment]
I think it should be that the returned object is too large but the `circular-json` package can't support this case well.

**Comment by Stngle** [comment]
> flatted

i try it by using `flatted` but encountered the same problem.

**Comment by Stngle** [comment]
> It looks like `circular-json` is deprecated right now and we should use `flatted` instead. Can you please try that as well?

i also encountered this problem when i use `flatted` in `macaca-reporter`, and i solve this problem by using `safe-json-stringify`.

**Comment by Stngle** [comment]
I try it by using flatted but encountered the same problem. I also encountered this problem when i use flatted in macaca-reporter, and i solve this problem by using safe-json-stringify.


The pull request link as follow:
https://github.com/mocha-parallel/mocha-parallel-tests/pull/223




------------------ 原始邮件 ------------------
发件人: "Dmitrii Sorin"<notifications@github.com>;
发送时间: 2019年4月9日(星期二) 晚上10:35
收件人: "mocha-parallel/mocha-parallel-tests"<mocha-parallel-tests@noreply.github.com>;
抄送: "Jalin"<1113591198@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mocha-parallel/mocha-parallel-tests] fix: circular jsonstringify (#223)




It looks like circular-json is deprecated right now and we should use flatted instead. Can you please try that as well?

**Comment by 1999** [comment]
As you can see the PR build is failing. Could you fix it please?

**Comment by Stngle** [comment]
> As you can see the PR build is failing. Could you fix it please?

i have fixed the PR build error, and as you can see, there is something wrong with ci. I have checked it but it seems nothing wrong with `json stringify` or `json parse` . Could you help me check it please?

**Comment by Stngle** [comment]
```
// dist/main/runner.js

    emitFinishEvents(onComplete) {
        this.emit('suite end', this.rootSuite);
        this.emit('end');
        if (onComplete) {
            onComplete(this.failures);
        }
    }
```

it maybe anything wrong in this event emitter.

**Comment by 1999** [comment]
@Stngle it would be great if you could manage this. Right now all tests in `mocha-parallel-tests` pass locally so probably your fix has a conflict with some of the tests if the PR build fails. Also, I can't just merge this change if there's no new test for it because there should be a failing case in master which your PR fixes.

**Pull request closed without merging**
